# Generated by Django 6.0 on 2026-01-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='digits',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='special',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='uppercase',
            field=models.BooleanField(default=True),
        ),
    ]
